# wrangler.toml
name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2025-09-03"

account_id = "5ff52dc210a86ff34a0dd3664bacb237"  # <-- your account id

[vars]
ENV = "prod"

[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"