name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2024-11-21"
workers_dev = true
kv_namespaces = [{ binding = "BRAIN", id = "${{ secrets.CF_KV_BRAIN_ID }}" }]

[vars]
ENV = "prod"

[placement]
mode = "smart"

[observability]
enabled = true
