# wrangler.toml — final

name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2025-09-03"

# ✅ GitHub Actions injects account_id from secrets; don't hardcode it.

# === Worker env vars ===
[vars]
ENV = "prod"

# === KV ===
[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"

# === Routes (Worker only) ===
# UI is served by Cloudflare Pages; leave routes only for the Worker.
[[routes]]
pattern = "maggie.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

# === Cron ===
[triggers]
crons = ["*/5 * * * *"]

# === Cloudflare Pages (for the /ui app) ===
[pages]
project_name = "assistant-ui"
build_output_dir = "ui/dist"