name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2024-09-03"

# Replace this with your real Cloudflare Account ID
account_id = "5ff52dc210a86ff34a0dd3664bacb237"

# Bindings for KV, environment variables, etc.
[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"

[vars]
ENV = "prod"