# wrangler.toml — final

name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2025-09-03"

# GitHub Actions injects CF_ACCOUNT_ID & token; don't hardcode account_id.

# === Worker env vars ===
[vars]
ENV = "prod"

# === KV ===
[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"

# === Routes (Worker only) ===
# UI is served by Cloudflare Pages; do NOT route assistant.* here.
[[routes]]
pattern = "maggie.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

# === Cron ===
[triggers]
crons = ["*/5 * * * *"]

[pages]
project_name = "assistant-ui"
build_output_dir = "ui/dist"
