# wrangler.toml — final

name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false   # we deploy on a custom domain/route
auth_type = "api_token"
account_id = "5ff52dc210a86ff34a0dd3664bacb237"
zone_id = "2cfbda5c5f45871836cfcf15285f5f13"

# The account_id and zone_id map to messyandmagnetic.com and are safe to commit.

# === Worker env vars (KEY NAMES, not secret values) ===
[vars]
ENV = "prod"
SECRET_BLOB = "thread-state"          # the raw secrets JSON key in KV
BRAIN_DOC_KEY = "PostQ:thread-state"  # the human-readable brain doc key in KV

# === KV binding ===
# Bind your Cloudflare KV as "BRAIN". The ID is taken from repo secrets:
# - CF_KV_POSTQ_NAMESPACE_ID (preferred)
# - CF_KV_NAMESPACE_ID (fallback)
# This avoids hard-coding IDs in the repo.
[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"

[[kv_namespaces]]
# Alias of BRAIN for Codex health checks and status mirroring.
# Update the ID if a dedicated Maggie KV namespace is provisioned.
binding = "MAGGIE"
id = "1b8cbbc4a2f8426194368cb39baded79"

[[kv_namespaces]]
# Optional secondary alias used by some scripts during migrations.
binding = "MAGGIE_KV"
id = "1b8cbbc4a2f8426194368cb39baded79"

# === Routes (Worker only) ===
[[routes]]
pattern = "maggie.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

[[routes]]
pattern = "assistant.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

[[routes]]
pattern = "messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

# === Cron triggers ===
[[triggers]]
schedule = "*/5 * * * *"

[[triggers]]
schedule = "0 7 * * *"

[[triggers]]
schedule = "30 3 * * *"

[[triggers]]
schedule = "0 * * * *"

# === Cloudflare Pages (UI app) ===
[pages]
project_name = "mags-site"
build_output_dir = "ui/dist"
