name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2025-09-03"

# Don’t put account_id here – GitHub Actions injects it via env var
# account_id = "..."

[vars]
ENV = "prod"

[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"