# wrangler.toml — final

name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false   # we deploy on a custom domain/route

# NOTE: account_id is supplied by GitHub Actions via secrets (don’t hardcode)

# === Worker env vars (KEY NAMES, not secret values) ===
[vars]
ENV = "prod"
SECRET_BLOB = "thread-state"          # the raw secrets JSON key in KV
BRAIN_DOC_KEY = "PostQ:thread-state"  # the human-readable brain doc key in KV

# === KV binding ===
# Bind your Cloudflare KV as "BRAIN". The ID is taken from repo secrets:
# - CF_KV_POSTQ_NAMESPACE_ID (preferred)
# - CF_KV_NAMESPACE_ID (fallback)
# This avoids hard-coding IDs in the repo.
[[kv_namespaces]]
binding = "BRAIN"
id = "1b8cbbc4a2f8426194368cb39baded79"

# === Routes (Worker only) ===
[[routes]]
pattern = "maggie.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

[[routes]]
pattern = "assistant.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

[[routes]]
pattern = "messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

# === Cron triggers ===
[triggers]
crons = ["*/5 * * * *"]

# === Cloudflare Pages (UI app) ===
[pages]
project_name = "mags-site"
build_output_dir = "ui/dist"
build_command = "pnpm --filter assistant-ui build"
