# wrangler.toml — final

name = "mags-assistant"
main = "worker/worker.ts"
compatibility_date = "2024-11-01"
# Enable Node.js builtins
compatibility_flags = ["nodejs_compat"]

# ✅ GitHub Actions injects account_id from secrets; don't hardcode it.

# === Worker env vars ===
[vars]
ENV = "prod"
SECRET_BLOB = "thread-state"
BRAIN_DOC_KEY = "PostQ:thread-state"

# === KV ===
[[kv_namespaces]]
binding = "BRAIN"
# prefer env-provided namespace id if available; otherwise use the one that already holds our keys
id = "${CF_KV_POSTQ_NAMESPACE_ID:-${CF_KV_NAMESPACE_ID}}"

# === Routes (Worker only) ===
# UI is served by Cloudflare Pages; leave routes only for the Worker.
[[routes]]
pattern = "maggie.messyandmagnetic.com/*"
zone_name = "messyandmagnetic.com"

# === Cron ===
[triggers]
crons = ["*/5 * * * *"]

# === Cloudflare Pages (for the /ui app) ===
[pages]
project_name = "mags-site"
build_output_dir = "ui/dist"
