name = "mags-runner"
main = "worker.ts"                    # path is relative to mags-runner/
account_id = "5ff52dc210a86ff34a0dd3664bacb237"
compatibility_date = "2024-08-01"
workers_dev = true

kv_namespaces = [
  { binding = "POSTQ", id = "1b8cbbc4a2f8426194368cb39baded79" }
]

triggers = { crons = ["*/10 * * * *"] }   # every 10 minutes