# mags-runner/wrangler.toml  (cron-only worker)

name = "mags-runner"
main = "worker.ts"                    # this file should be inside mags-runner/
account_id = "5ff52dc210a86ff34a0dd3664bacb237"
compatibility_date = "2024-08-01"

# No routes; this worker is NOT on your domain
workers_dev = true                    # helpful for testing

# reuse the same KV namespace
kv_namespaces = [
  { binding = "POSTQ", id = "1b8cbbc4a2f8426194368cb39baded79" }
]

# Cron schedule (every 10 minutes)
triggers = { crons = ["*/10 * * * *"] }