name: GH_PAT Debug
on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [kick-gh-pat-debug]
  workflow_call:
permissions:
  contents: read
  actions: write
jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Diagnostics
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Using GitHub token for repo: $GITHUB_REPOSITORY"
          gh auth status || true

      - name: Check GitHub token presence
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is NOT set"; exit 2
          else
            echo "GITHUB_TOKEN is set"
          fi
      - name: GET /user headers with GITHUB_TOKEN (redacted)
        run: |
          set -e
          curl -sI -H "Authorization: Bearer $GH_TOKEN" https://api.github.com/user \
          | tr -d '\r' | awk 'BEGIN{IGNORECASE=1}/^x-oauth-scopes|^status|^date/ {print}'
      - name: Try workflow dispatch for token-smoke (expect 204)
        env:
          OWNER: messyandmagneticassistant
          REPO: mags-assistant
        run: |
          CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/token-smoke.yml/dispatches \
            -d '{"ref":"main"}')
          echo "Dispatch /token-smoke.yml HTTP: $CODE"
          test "$CODE" = "204" || exit 3
