name: Deploy Maggie (Workers + KV bootstrap)
on:
  push:
    branches: [main]
    paths:
      - "worker/**"
      - "mags-runner/**"
      - "wrangler.toml"
      - "mags-runner/wrangler.toml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "config/thread-state.json"  # file will be created in CI
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN:       ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID:              ${{ secrets.CF_ACCOUNT_ID }}
      CF_ZONE_ID:                 ${{ secrets.CF_ZONE_ID }}
      CF_KV_POSTQ_NAMESPACE_ID:   ${{ secrets.CF_KV_POSTQ_NAMESPACE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm i --frozen-lockfile=false

      - name: Create config/thread-state.json from secret
        run: |
          mkdir -p config
          printf '%s' "${{ secrets.THREAD_STATE_JSON }}" > config/thread-state.json

      - name: "Sync KV: thread-state"
        run: |
          echo "Uploading config/thread-state.json to KV key 'thread-state' ..."
          npx wrangler kv key put \
            --namespace-id "${CF_KV_POSTQ_NAMESPACE_ID}" \
            thread-state \
            --path=config/thread-state.json

      - name: Deploy public worker
        run: npx wrangler deploy -c wrangler.toml --minify

      - name: Deploy runner worker
        run: npx wrangler deploy -c mags-runner/wrangler.toml --minify
