name: Deploy Worker

on:
  push:
  workflow_dispatch: {}

concurrency:
  group: deploy-worker
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Node only. DO NOT set cache: pnpm here.
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) Install & activate pnpm with Corepack (works on GitHub runners)
      - name: Activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm -v
          node -v

      # 3) Install deps
      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      # 4) (optional) Show Wrangler version
      - name: Show Wrangler version
        run: npx wrangler --version

      # 5) Deploy / upload version
      - name: Publish (main) or upload version (branches)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            npx wrangler deploy -c wrangler.toml
          else
            npx wrangler versions upload -c wrangler.toml
          fi