name: Deploy UI

on:
  workflow_dispatch:

concurrency:
  group: deploy-ui
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm -v

      # Install deps for ALL packages (root + workspaces)
      - name: Install deps
        run: pnpm -r install --no-frozen-lockfile

      # Build ONLY the UI workspace
      - name: Build UI
        run: pnpm --filter assistant-ui... build

      # Deploy built /assistant-ui/dist to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: mags-ui            # your Pages project name
          directory: assistant-ui/dist    # output directory of the UI build