name: Deploy UI

on:
  push:
    branches: [ main ]
    paths:
      - "ui/**"
      - ".github/workflows/deploy-ui.yml"
      - "wrangler.toml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - name: Enable PNPM via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@9.12.0 --activate

      - name: Enable PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Corepack version (non-blocking)
        run: corepack --version || true

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build UI
        run: pnpm -w --filter ui build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: wrangler pages deploy ui

      - name: Notify Telegram of deploy
        if: always()
        run: |
          MSG="🌸 Website deployed: https://messyandmagnetic.com"
          if [ "${{ job.status }}" != "success" ]; then
            MSG="❌ Website deploy failed."
          fi
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            --data-urlencode text="$MSG"

