name: Maggie Diagnostics

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest

    steps:
      - name: Health check (public worker)
        run: |
          echo "Checking Maggie public worker..."
          curl -sS https://maggie.messyandmagnetic.com/health || exit 1

      - name: Health check (runner worker)
        run: |
          echo "Checking Maggie runner worker..."
          curl -sS https://mags-runner.messyandmagnetic.workers.dev/health || exit 1

      - name: TikTok ping (Browserless session check)
        run: |
          echo "Pinging TikTok Browserless endpoint..."
          curl -sS "https://maggie.messyandmagnetic.com/tasks/tiktok/ping?key=${{ secrets.WORKER_CRON_KEY }}" || exit 1