name: Drive Watch

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  watch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          pnpm -v || npm install -g pnpm
      - run: pnpm install --frozen-lockfile=false
      - name: Run watcher
        env:
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
          RAW_CLIPS_FOLDER_ID: ${{ secrets.RAW_CLIPS_FOLDER_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          HQ_DATABASE_ID: ${{ secrets.HQ_DATABASE_ID }}
          GAS_INTAKE_URL: ${{ secrets.GAS_INTAKE_URL }}
        run: pnpm tsx scripts/drive_watch.mjs
      - name: Commit cache
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(ci): update drive_seen cache"
          title: "chore(ci): update drive_seen cache"
          branch: "ci/drive-seen"
          add-paths: data/drive_seen.json
