name: Route & Telegram Health

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '30 3 * * *'

jobs:
  route-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Set up pnpm
        run: corepack prepare pnpm@latest --activate
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm exec tsc --noEmit
      - name: Run route & telegram test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        run: pnpm dlx tsx worker/scripts/testRoutesAndTelegram.ts
