name: Run All

on:
  workflow_dispatch:

jobs:
  make:
    uses: ./.github/workflows/make-sync.yml

  create:
    uses: ./.github/workflows/create-routes.yml

  seed:
    uses: ./.github/workflows/sync-brain.yml
