name: Social Orchestrator

on:
  schedule:
    - cron: "7 15 * * *" # daily; adjust later based on analytics
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Enable PNPM via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.15.0 --activate
          pnpm --version
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Run social (dryrun unless enabled)
        env:
          ENABLE_SOCIAL: ${{ secrets.ENABLE_SOCIAL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # add any TikTok/Instagram secrets required by your scripts
        run: |
          if [ "${ENABLE_SOCIAL}" = "true" ]; then
            pnpm run social:dryrun | tee social.log
          else
            echo "Posting disabled (ENABLE_SOCIAL!=true). Running analysis only."
            pnpm run social:dryrun | tee social.log
          fi
