name: Social Orchestrator

on:
  workflow_dispatch:
    inputs:
      override:
        description: 'Optional JSON to override endpoints/config'
        required: false
        default: ''
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10.15.0'
  NODE_OPTIONS: '--enable-source-maps'
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
  POST_THREAD_SECRET: ${{ secrets.POST_THREAD_SECRET }}
  THREAD_STATE_JSON:  ${{ secrets.THREAD_STATE_JSON }}

jobs:
  dryrun:
    name: Dryrun (no posting)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Set up Node (no pnpm cache here)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 2) Install pnpm and ensure it's on PATH
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      # Fallback in case the runner image changes and pnpm isn't exposed
      - name: Ensure pnpm is available
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            npm i -g pnpm@${{ env.PNPM_VERSION }}
          fi
          pnpm --version

      # 3) Cache pnpm store
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 4) Install deps
      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      # 5) Run dryrun
      - name: Run social dryrun
        run: pnpm run social:dryrun

      # Notify if anything in this job fails
      - name: On failure, send Telegram alert
        if: failure() && env.TELEGRAM_BOT_TOKEN && env.TELEGRAM_CHAT_ID
        run: |
          MSG="❌ Social DRYRUN failed on \`${{ github.repository }}\` @ ${{ github.ref_name }} (run ${{ github.run_id }})"
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MSG"

  orchestrate:
    name: Orchestrate queue (post/schedule)
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Ensure pnpm is available
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            npm i -g pnpm@${{ env.PNPM_VERSION }}
          fi
          pnpm --version

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Orchestrate queue
        run: pnpm tsx src/social/orchestrate.ts '${{ github.event.inputs.override }}'

      - name: On failure, send Telegram alert
        if: failure() && env.TELEGRAM_BOT_TOKEN && env.TELEGRAM_CHAT_ID
        run: |
          MSG="❌ Social ORCHESTRATE failed on \`${{ github.repository }}\` @ ${{ github.ref_name }} (run ${{ github.run_id }})"
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MSG"