name: Stripe Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '10.15.0'
  NODE_OPTIONS: '--enable-source-maps'
  STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  STRIPE_WEBHOOK_SEC: ${{ secrets.STRIPE_WEBHOOK_SEC }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  sync:
    name: Run Stripe sync
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Run sync
        run: pnpm tsx scripts/stripe-sync.ts
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SEC: ${{ secrets.STRIPE_WEBHOOK_SEC }}

      - name: On failure, send Telegram alert
        if: failure() && env.TELEGRAM_BOT_TOKEN && env.TELEGRAM_CHAT_ID
        run: |
          MSG="❌ Stripe Sync failed on \`${{ github.repository }}\` @ ${{ github.ref_name }} (run ${{ github.run_id }})"
          curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MSG"