name: Stripe Sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Reconcile catalog
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: pnpm tsx src/commerce/sync.ts > stripe-summary.json
      - uses: actions/upload-artifact@v4
        with:
          name: stripe-summary
          path: stripe-summary.json
