name: Stripe Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *" # daily at 06:00 UTC

concurrency:
  group: stripe-sync-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "10.15.0"
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  reconcile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Reconcile products/plans
        env:
          STRIPE_SECRET_KEY: ${{ env.STRIPE_SECRET_KEY }}
        run: pnpm tsx src/commerce/sync.ts