name: Sync Brain to Cloudflare KV

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are we running this?"
        required: false
        default: "manual"
  schedule:
    - cron: '30 3 * * *'  # 03:30 UTC (21:30 ABQ during DST)
  workflow_call:
    inputs:
      reason:
        required: false
        type: string
        default: "manual"

permissions:
  contents: read

jobs:
  sync:
    uses: ./.github/workflows/reusable-brain-sync.yml
    secrets: inherit
    with:
      reason: ${{ inputs.reason || github.event.inputs.reason || '' }}
