name: Sync Brain to KV

on:
  workflow_dispatch:
  schedule:
    # Nightly at 03:30 Albuquerque time (America/Denver)
    - cron: "30 9 * * *"

jobs:
  sync-brain:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Ensure pnpm exists and is on PATH
      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check pnpm
        run: pnpm --version

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      # Update KV with docs/brain.md
      - name: Update Brain KV
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_KV_POSTQ_NAMESPACE_ID: ${{ secrets.CF_KV_POSTQ_NAMESPACE_ID }}
          # Optional passthroughs used by your scripts
          BRAIN_DOC_KEY: PostQ:thread-state
          SECRET_BLOB: thread-state
        run: |
          # Prefer pnpm exec, but fall back to npx if needed
          if command -v pnpm >/dev/null 2>&1; then
            pnpm exec tsx scripts/updateBrain.ts
          else
            npx tsx scripts/updateBrain.ts
          fi

      # Verify parity/ping
      - name: Ping / verify
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_KV_POSTQ_NAMESPACE_ID: ${{ secrets.CF_KV_POSTQ_NAMESPACE_ID }}
        run: |
          if command -v pnpm >/dev/null 2>&1; then
            pnpm exec tsx scripts/brainPing.ts
          else
            npx tsx scripts/brainPing.ts
          fi
