name: Sync Brain (KV ⇄ repo)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Seed thread state blob
        env:
          POST_THREAD_SECRET: ${{ secrets.POST_THREAD_SECRET }}
        run: |
          set -euo pipefail
          curl --fail -sS \
            -H "Authorization: Bearer ${POST_THREAD_SECRET}" \
            -H "Content-Type: application/json" \
            --data-binary @config/thread-state.json \
            https://maggie.messyandmagnetic.com/init-blob
          echo "Thread state seed request completed"

      - name: Verify diag config
        env:
          POST_THREAD_SECRET: ${{ secrets.POST_THREAD_SECRET }}
        run: |
          set -euo pipefail
          curl --fail -sS \
            -H "Authorization: Bearer ${POST_THREAD_SECRET}" \
            https://maggie.messyandmagnetic.com/diag/config \
            -o diag-config.json
          if command -v jq >/dev/null 2>&1; then
            KEY_SAMPLE=$(jq -r 'paths(scalars) | map(tostring) | unique | .[:10] | join(", ")' diag-config.json 2>/dev/null || true)
            if [ -n "$KEY_SAMPLE" ]; then
              echo "diag/config sample keys: $KEY_SAMPLE"
            else
              echo "diag/config retrieved (no scalar key paths detected)"
            fi
          else
            echo "diag/config retrieved ($(wc -c < diag-config.json) bytes)"
          fi
