name: Sync Brain (KV ⇄ repo)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are we running this?"
        required: false
        default: "manual"
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 3 * * *"   # 03:30 UTC (~9:30pm ABQ during DST)
  workflow_call:
    secrets:
      POST_THREAD_SECRET:
        required: true

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Seed KV
        run: |
          curl -X POST https://maggie.messyandmagnetic.com/init-blob \
            -H "Authorization: Bearer ${{ secrets.POST_THREAD_SECRET }}" \
            -H "Content-Type: application/json" \
            --data-binary @config/thread-state.json

      - name: Smoke Test
        run: |
          curl -sS https://maggie.messyandmagnetic.com/diag/config \
            -H "Authorization: Bearer ${{ secrets.POST_THREAD_SECRET }}"
