name: Token Smoke
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if GH_PAT not set
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is not configured in repo secrets"; exit 1
          fi
      - name: Call GitHub API with GH_PAT
        run: |
          set -e
          # Show scopes
          curl -sS -D headers.txt -o /dev/null \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/user
          echo "---- x-oauth-scopes ----"
          grep -i '^x-oauth-scopes:' headers.txt || true
          echo "---- rate-limit ----"
          grep -i '^x-ratelimit-' headers.txt || true
          # Try listing workflows (should be 200)
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows)
          echo "List workflows HTTP $code"
          [ "$code" = "200" ] || (echo "Expected 200; got $code"; exit 1)
