name: GH_PAT Smoke
on: { workflow_dispatch: {} }
permissions:
  actions: write
  contents: read
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Require GH_PAT
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is not set in repo secrets"; exit 1
          fi
      - name: Show token scopes (header only)
        env: { GH_PAT: ${{ secrets.GH_PAT }} }
        run: |
          curl -sI -H "Authorization: Bearer $GH_PAT" https://api.github.com/user \
          | tr -d '\r' | grep -i '^x-oauth-scopes' || true
      - name: Dispatch sync-brain and assert 204
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          OWNER: messyandmagneticassistant
          REPO: mags-assistant
        run: |
          CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $GH_PAT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/workflows/sync-brain.yml/dispatches \
            -d '{"ref":"main","inputs":{"reason":"token-smoke"}}')
          echo "Dispatch HTTP: $CODE"
          test "$CODE" = "204" || { echo "Expected 204"; exit 1; }
