name: Weekly Digest

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        run: |
          corepack enable
          pnpm -v || npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run weekly digest
        run: npx tsx scripts/weeklyDigest.ts
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_DB_LOGS: ${{ secrets.NOTION_DB_LOGS }}
          NOTION_DONOR_PAGE_ID: ${{ secrets.NOTION_DONOR_PAGE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
